language: python
services:
  -  docker
python:
  -  "2.7"
install:
  -  make deps
script:
  -  make test
  -  make lint
  -  make docker_build
  -  make docker_push
  -  make test_xunit
deploy:
  provider: heroku
  app: enigmatic-beach-03953
  api_key: ${HEROKU_API_KEY}
